### ISSUE TITLE
Windows compatibility 

### ISSUE THREAD

**Issue by wgranados** [wgma00/PokemonShowdownBot#11]
The original project is able to run on windows binaries, this branch of the project however cannot because it uses many libriaries that are unix/linux exlcusive like the `gcalccmd` library. I will look into finding equivalent software that provide the same service, but I recommend anyone not interested in these features and are only interested in having a functional version in Windows to use the original project as your starting point.

**Comment by wgranados** [comment]
First attempt at resolving this is a bust.
Tried a hacky way to run the linux libraries that I use for the ``.calc`` and ``LaTeX`` related commands on the Windows 10 platform by piping the necessary commands to the WSL (bash on ubuntu binary). Unfortunately the ``subprocess`` module returned error code ``4294967295``,  and not the zero-exit code required. Turns out that this issue is resolved on the Windows insider builds, __but__, this bug fix won't be shipped to consumer versions of Windows 10,  until the next installment of windows rolls around. 👎  

Guess I'll have to try another alternative to getting these features working on the normal Windows 10 versions.

More information on this issue is here: [BashOnWindows](https://github.com/Microsoft/BashOnWindows/issues/2)

For the calculator related notes, I'll probably have to use a library that isn't the GNOME gcalccmd, or 
Some alternatives I can think of to get ``.calc`` command working on all platforms is to include the source files from [GNOME's public repo](https://github.com/GNOME/gnome-calculator/blob/master/src/gcalccmd.vala), and compiling those vala libraries on the systems. Or just use the ``eval`` function for python with some very strict input sanitation (although the route suffers from floating point arithmetic errors, sadly).

On a semi motivational note, I think I might be able to run the ``LaTeX`` related commands by simply installing the LaTeX related binaries on Windows 10. When I was debugging by calling the normal ``cmd.exe`` with subprocess. Here's the [output](https://gyazo.com/5d2373abcb5e14e5d18bfbca7a3c8fed)

**Comment by wgma00** [comment]
Latex is now cross platform, solution can be found here: 890a3f9c6bd4de12ee90eb826469e8c72e96b31a

**Comment by wgranados** [comment]
Piping works now, and is implemented in the latest  [commit](https://github.com/wgma00/PokemonShowdownBot/commit/425781745939835ab305aacc26d2bf3fd9aa7c35). Although now I'm left wondering what's the point of piping linux only comands to ubuntu bash when a user can just run the software inside ubuntu bash, haha.
