### ISSUE TITLE
project not running on ubuntu bash port

### ISSUE THREAD

**Issue by wgranados** [wgma00/PokemonShowdownBot#6]
There is an issue with the `websocket-clent` module. I have already browsed through their source code but haven't been able to figure out why it does not work. This is just a fair warning for anyone who tries to run this project on windows, the websocket will not open!

**Comment by QuiteQuiet** [comment]
Correction: It runs on Windows 7/8/10, but not specifically the Ubuntu Bash beta on Windows 10.

**Comment by wgranados** [comment]
This is correct. The original project will run on Windows binaries, but it will not run on the Ubuntu Bash beta platform. After some research I believe this is due to Python's platform dependent options, specifically use of `def sample(x, **options):`  in the [websocket-client](https://github.com/liris/websocket-client/blob/master/websocket/_core.py#L179). Which according to Python documentation is not available on all platforms. Hopefully this issue will be fixed by the [Ubuntu Bash beta](https://github.com/Microsoft/BashOnWindows) maintainers.

**Comment by wgranados** [comment]
This issue is now fixed with the release of the windows 10 creator update.
https://blogs.windows.com/windowsexperience/2017/04/11/how-to-get-the-windows-10-creators-update/#DyAY3y5Gf20CojVe.97
