### ISSUE TITLE
redirects

### ISSUE THREAD

**Issue by wgranados** [wgma00/PokemonShowdownBot#8]
there appears to be something funky going on when the bot is redirected.

**Comment by QuiteQuiet** [comment]
This isn't my branch, but done in https://github.com/QuiteQuiet/PokemonShowdownBot/commit/5e3d0cd3b86867999cdb4e488d64fc001d80f984

**Comment by wgranados** [comment]
I will integrate this change into my branch when I find some free time.

**Comment by wgranados** [comment]
I have merged the branches so this is now fixed.
